### ISSUE TITLE
MySQL Schema errors

### ISSUE THREAD

**Issue by VA2XJM** [hammady/group-order#2]
The schema file contains various errors...

`ALTER TABLE `New Table` RENAME TO `user`, ENGINE = InnoDB;` should be `ALTER TABLE `new table` RENAME TO `user`, ENGINE = InnoDB;`

`#3-12-2008
CREATE TABLE `cnfg` (
  `server` VARCHAR(100) NOT NULL,
  `ipmsg_path` VARCHAR(100) NOT NULL
)
ENGINE = InnoDB;`
That Table already exists... should be altered.

`#4-12-2008
ALTER TABLE `shop` ADD COLUMN `delivery` DECIMAL(10,2) NOT NULL AFTER `date_modified`
, ENGINE = InnoDB;` Already exists.

And much more... You should re-extract table structure currently in use and make a new file for update.

**Comment by hammady** [comment]
Please specify the exact command that you run because it doesn't give such errors to me. Please also attach the output.

**Comment by VA2XJM** [comment]
At the time, I think I was loading both SQL files one after another, I just can't remember exactly but my guess is I first started with data.sql then schema.sql... I will try again today and gives you an update...

**Comment by VA2XJM** [comment]
Correction, It seems to work... another problem is deprecated code... see new ticket.
